
development:
  adapter: postgresql
  template: template0
  database: mini_pos
  pool: 5
  username: mini_pos
  password:

test:
  adapter: postgresql
  template: template0
  database: mini_pos_test
  pool: 5
  username: mini_pos
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mini_pos_production
  pool: 5
  username: mini_pos
  password:
