development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
# development:
#   adapter: postgresql
#   encoding: unicode
#   database: mini_pos_development
#   pool: 5
#   username: mini_pos
#   password:
test:
  adapter: postgresql
  encoding: unicode
  database: mini_pos_test
  pool: 5
  username: mini_pos
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mini_pos_production
  pool: 5
  username: mini_pos
  password:
